#pragma once

enum prefsbuttonindex {
  PREFS_BUTTON_STYLE_CUSTOMIZATION,
  PREFS_BUTTON_FONT_CONFIG,
  PREFS_BUTTON_FONTSIZE,
  PREFS_BUTTON_LINE_SPACING,
  PREFS_BUTTON_PARASPACING,
  PREFS_BUTTON_ORIENTATION,
  PREFS_BUTTON_HANDEDNESS,
  PREFS_BUTTON_TIME24H,
  PREFS_BUTTON_TIME_REMAINING,
  PREFS_BUTTON_REOPEN_LAST_BOOK,
  PREFS_BUTTON_COLORMODE,
  PREFS_BUTTON_LIBRARY_VIEW,
  PREFS_BUTTON_CIRCLE_PAD_PAGE_TURN,
  PREFS_BUTTON_LIBRARY_SORT,
  PREFS_BUTTON_BOOK_INFO,
  PREFS_BUTTON_INDEX,
  PREFS_BUTTON_BOOKMARKS,
  PREFS_BUTTON_RESET_DEFAULTS,
  PREFS_BUTTON_CLEAR_CACHE,
  PREFS_BUTTON_PUBLISHER_TEXT_INDENT,
  PREFS_BUTTON_PUBLISHER_BLOCK_MARGINS,
  PREFS_BUTTON_EXPORT_HIGHLIGHTS,
  PREFS_BUTTON_SYNC_DEVICES,
  PREFS_BUTTON_COUNT
};
